### ISSUE TITLE
No way to run the code. 

### ISSUE THREAD

**Issue by cpcharland** [Lee-Jiho/Lee_CSCI2270_FinalProject#4]
The only way that I would be able to run your code would be if i created a project in Code::Blocks and then compile it myself, also it doesn't compile when I try to compile it. You should upload a executable that i could run to evaluate your code.

**Comment by Lee-Jiho** [comment]
Make sure that you're running main.cpp and not finalLinkedLists.cpp

**Comment by cpcharland** [comment]
Yeah, it's throwing about 20 errors. in your folder for the project, there should be a sub folder called bin and in there another folder called debug. in the debug folder there is an executable, upload that so we can not worry about this part
